// 30 levels: 10 easy, 10 medium, 10 hard
// Each level matches the existing level shape used by useGameStore

export const ALL_LEVELS = {
  easy: [
    {
      id: 'e1', num: 1,
      title: 'Hello, World!',
      description: 'Run a single synchronous log',
      hint: 'Synchronous code goes straight to the Call Stack!',
      code: [{ text: 'console.log("Hello");', type: 'sync', color: '#4ade80' }],
      balls: [{ id: 'b1', label: '"Hello"', type: 'sync', target: 'callstack' }],
      placementOrder: ['b1'],
      flow: [{ ballId: 'b1', type: 'execute', component: 'callstack', output: 'Hello', animationPath: ['callstack'] }],
    },
    {
      id: 'e2', num: 2,
      title: 'Two Logs',
      description: 'Run two synchronous statements in order',
      hint: 'Code runs top to bottom. First in, first executed!',
      code: [
        { text: 'console.log("A");', type: 'sync', color: '#4ade80' },
        { text: 'console.log("B");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"A"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"B"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'A', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'B', animationPath: ['callstack'] },
      ],
    },
    {
      id: 'e3', num: 3,
      title: 'Three in a Row',
      description: 'Three synchronous console logs',
      hint: 'The Call Stack is LIFO — but for top-level code it runs in order.',
      code: [
        { text: 'console.log("1");', type: 'sync', color: '#4ade80' },
        { text: 'console.log("2");', type: 'sync', color: '#4ade80' },
        { text: 'console.log("3");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"1"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"2"', type: 'sync', target: 'callstack' },
        { id: 'b3', label: '"3"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: '1', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: '2', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: '3', animationPath: ['callstack'] },
      ],
    },
    {
      id: 'e4', num: 4,
      title: 'Meet the Promise',
      description: 'A resolved Promise schedules a microtask',
      hint: 'Promise.resolve().then() creates a microtask — runs after sync!',
      code: [
        { text: 'console.log("sync");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.resolve().then(() =>', type: 'promise', color: '#c084fc' },
        { text: '  console.log("micro"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"sync"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"micro"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'sync', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'micro', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'e5', num: 5,
      title: 'Timeout Basics',
      description: 'setTimeout defers a callback via the Web API',
      hint: 'setTimeout goes: Call Stack → Web API → Macrotask Queue → Call Stack',
      code: [
        { text: 'console.log("now");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("later"), 0);', type: 'timeout', color: '#60a5fa' },
      ],
      balls: [
        { id: 'b1', label: '"now"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"later"', type: 'timeout', target: 'macrotask' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'now', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'later', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'e6', num: 6,
      title: 'Sync Sandwich',
      description: 'Sync code before and after a Promise',
      hint: 'Sync runs fully before any microtask gets a chance!',
      code: [
        { text: 'console.log("Start");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.resolve().then(() => console.log("Mid"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("End");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"Start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"Mid"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"End"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'Start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'End', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'Mid', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'e7', num: 7,
      title: 'Timeout Sandwich',
      description: 'Sync code around a setTimeout',
      hint: 'setTimeout always runs last — even with 0ms delay!',
      code: [
        { text: 'console.log("First");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("Third"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'console.log("Second");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"First"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"Third"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"Second"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'First', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'Second', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'Third', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'e8', num: 8,
      title: 'Promise Pair',
      description: 'Two promises both schedule microtasks',
      hint: 'Both microtasks queue up and drain before any macrotask!',
      code: [
        { text: 'Promise.resolve().then(() => console.log("P1"));', type: 'promise', color: '#c084fc' },
        { text: 'Promise.resolve().then(() => console.log("P2"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"P1"', type: 'promise', target: 'microtask' },
        { id: 'b2', label: '"P2"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'P1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'P2', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'e9', num: 9,
      title: 'Timeout After Sync',
      description: 'Two sync logs then a timeout',
      hint: 'Web API holds the timer, then passes it to the Macrotask Queue.',
      code: [
        { text: 'console.log("X");', type: 'sync', color: '#4ade80' },
        { text: 'console.log("Y");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("Z"), 0);', type: 'timeout', color: '#60a5fa' },
      ],
      balls: [
        { id: 'b1', label: '"X"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"Y"', type: 'sync', target: 'callstack' },
        { id: 'b3', label: '"Z"', type: 'timeout', target: 'macrotask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'X', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'Y', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'Z', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'e10', num: 10,
      title: 'The Easy Grand Finale',
      description: 'Sync + Promise + setTimeout together',
      hint: 'Order: Sync → Microtask → Macrotask. Remember this forever!',
      code: [
        { text: 'console.log("Start");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("Timeout"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("Promise"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("End");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"Start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"Timeout"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"Promise"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"End"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'Start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'End', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'Promise', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'Timeout', animationPath: ['macrotask', 'callstack'] },
      ],
    },
  ],

  medium: [
    {
      id: 'm1', num: 1,
      title: 'Chained Promise',
      description: 'A .then() chains onto another .then()',
      hint: 'Each .then() schedules a NEW microtask when the previous one resolves.',
      code: [
        { text: 'console.log("start");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.resolve()', type: 'promise', color: '#c084fc' },
        { text: '  .then(() => console.log("p1"))', type: 'promise', color: '#c084fc' },
        { text: '  .then(() => console.log("p2"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"p1"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"p2"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'p1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'p2', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'm2', num: 2,
      title: 'Micro Before Macro',
      description: 'A microtask always beats a macrotask',
      hint: 'Even if setTimeout is registered first, microtasks drain the queue before it runs!',
      code: [
        { text: 'setTimeout(() => console.log("macro"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("micro"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"macro"', type: 'timeout', target: 'macrotask' },
        { id: 'b2', label: '"micro"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'micro', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'macro', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm3', num: 3,
      title: 'The Classic Order',
      description: 'Predict the full output order',
      hint: 'sync → all microtasks → first macrotask. Repeat.',
      code: [
        { text: 'console.log("1");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("3"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("4");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"1"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"2"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"3"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"4"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: '1', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: '4', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: '3', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: '2', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm4', num: 4,
      title: 'Double Timeout',
      description: 'Two setTimeouts queue in registration order',
      hint: 'Multiple macrotasks run in the order they were registered.',
      code: [
        { text: 'setTimeout(() => console.log("T1"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'setTimeout(() => console.log("T2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'console.log("sync");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"T1"', type: 'timeout', target: 'macrotask' },
        { id: 'b2', label: '"T2"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"sync"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'sync', animationPath: ['callstack'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'T1', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'T2', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm5', num: 5,
      title: 'Promise Before Sync?',
      description: 'Does a Promise run before synchronous code?',
      hint: 'No! Sync code always finishes first before the microtask queue is drained.',
      code: [
        { text: 'Promise.resolve().then(() => console.log("async"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("sync");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"async"', type: 'promise', target: 'microtask' },
        { id: 'b2', label: '"sync"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'sync', animationPath: ['callstack'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'async', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'm6', num: 6,
      title: 'Three Queues',
      description: 'Sync, microtask, and macrotask all in play',
      hint: 'After sync completes, microtask queue drains fully before first macrotask runs.',
      code: [
        { text: 'console.log("A");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("C"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("B"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"A"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"C"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"B"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'A', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'B', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'C', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm7', num: 7,
      title: 'Async Illusion',
      description: 'async/await is syntactic sugar over Promises',
      hint: 'await suspends and the continuation becomes a microtask.',
      code: [
        { text: 'console.log("before");', type: 'sync', color: '#4ade80' },
        { text: 'async function f(){ await null; console.log("await"); }', type: 'promise', color: '#c084fc' },
        { text: 'f();', type: 'promise', color: '#c084fc' },
        { text: 'console.log("after");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"before"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"await"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"after"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'before', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'after', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'await', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'm8', num: 8,
      title: 'Queue Race',
      description: 'Two microtasks race before a macrotask',
      hint: 'All queued microtasks run before even a single macrotask fires.',
      code: [
        { text: 'setTimeout(() => console.log("T"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("P1"));', type: 'promise', color: '#c084fc' },
        { text: 'Promise.resolve().then(() => console.log("P2"));', type: 'promise', color: '#c084fc' },
      ],
      balls: [
        { id: 'b1', label: '"T"', type: 'timeout', target: 'macrotask' },
        { id: 'b2', label: '"P1"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"P2"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'P1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'P2', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'T', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm9', num: 9,
      title: 'Nested Timeout',
      description: 'A timeout inside a timeout',
      hint: 'The inner setTimeout is only registered when the outer callback runs.',
      code: [
        { text: 'console.log("outer sync");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => {', type: 'timeout', color: '#60a5fa' },
        { text: '  console.log("outer cb");', type: 'timeout', color: '#60a5fa' },
        { text: '  setTimeout(() => console.log("inner cb"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: '}, 0);', type: 'timeout', color: '#60a5fa' },
      ],
      balls: [
        { id: 'b1', label: '"outer sync"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"outer cb"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"inner cb"', type: 'timeout', target: 'macrotask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'outer sync', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'outer cb', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b3', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'inner cb', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'm10', num: 10,
      title: 'Medium Boss',
      description: 'Full async gauntlet: sync + 2 microtasks + 2 macrotasks',
      hint: 'Stay calm: sync finishes → all microtasks → macrotasks one by one.',
      code: [
        { text: 'console.log("S");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("T1"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("P1"));', type: 'promise', color: '#c084fc' },
        { text: 'setTimeout(() => console.log("T2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("P2"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("E");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"S"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"T1"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"P1"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"T2"', type: 'timeout', target: 'macrotask' },
        { id: 'b5', label: '"P2"', type: 'promise', target: 'microtask' },
        { id: 'b6', label: '"E"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4', 'b5', 'b6'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'S', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b5', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b6', type: 'execute', component: 'callstack', output: 'E', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'P1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b5', type: 'execute', component: 'callstack', output: 'P2', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'T1', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'T2', animationPath: ['macrotask', 'callstack'] },
      ],
    },
  ],

  hard: [
    {
      id: 'h1', num: 1,
      title: 'Microtask Flood',
      description: 'A microtask that queues another microtask',
      hint: 'New microtasks added during microtask execution run before ANY macrotask.',
      code: [
        { text: 'console.log("start");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.resolve().then(() => {', type: 'promise', color: '#c084fc' },
        { text: '  console.log("p1");', type: 'promise', color: '#c084fc' },
        { text: '  Promise.resolve().then(() => console.log("p2"));', type: 'promise', color: '#c084fc' },
        { text: '});', type: 'promise', color: '#c084fc' },
        { text: 'console.log("end");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"p1"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"p2"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"end"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'end', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'p1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'p2', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h2', num: 2,
      title: 'Async Await Dance',
      description: 'async/await with a timeout mixed in',
      hint: 'Each await resumes as a microtask. The timeout waits for ALL microtasks.',
      code: [
        { text: 'async function run() {', type: 'promise', color: '#c084fc' },
        { text: '  console.log("A");', type: 'sync', color: '#4ade80' },
        { text: '  await Promise.resolve();', type: 'promise', color: '#c084fc' },
        { text: '  console.log("C");', type: 'promise', color: '#c084fc' },
        { text: '}', type: 'promise', color: '#c084fc' },
        { text: 'run();', type: 'sync', color: '#4ade80' },
        { text: 'console.log("B");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"A"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"C"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"B"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'A', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'B', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'C', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h3', num: 3,
      title: 'Promise Chain Trap',
      description: '.then() inside setTimeout — when does it run?',
      hint: 'The Promise inside setTimeout is only created when the macrotask fires.',
      code: [
        { text: 'console.log("1");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => {', type: 'timeout', color: '#60a5fa' },
        { text: '  Promise.resolve().then(() => console.log("3"));', type: 'promise', color: '#c084fc' },
        { text: '  console.log("2");', type: 'timeout', color: '#60a5fa' },
        { text: '}, 0);', type: 'timeout', color: '#60a5fa' },
      ],
      balls: [
        { id: 'b1', label: '"1"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"2"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"3"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: '1', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: '2', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: '3', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h4', num: 4,
      title: 'The Illusion of Zero',
      description: 'setTimeout 0 vs Promise — who wins?',
      hint: 'setTimeout(fn, 0) is still a macrotask. Promises always cut the line.',
      code: [
        { text: 'setTimeout(() => console.log("timeout"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("promise"));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("sync");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"timeout"', type: 'timeout', target: 'macrotask' },
        { id: 'b2', label: '"promise"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"sync"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'sync', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'promise', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'timeout', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'h5', num: 5,
      title: 'Triple Threat',
      description: 'Sync, chained promises, and two timeouts',
      hint: 'The chained microtask (p2) runs before any macrotask fires.',
      code: [
        { text: 'console.log("S");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("T1"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("P1")).then(() => console.log("P2"));', type: 'promise', color: '#c084fc' },
        { text: 'setTimeout(() => console.log("T2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'console.log("E");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"S"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"T1"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"P1"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"P2"', type: 'promise', target: 'microtask' },
        { id: 'b5', label: '"T2"', type: 'timeout', target: 'macrotask' },
        { id: 'b6', label: '"E"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4', 'b5', 'b6'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'S', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b5', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b6', type: 'execute', component: 'callstack', output: 'E', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'P1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b4', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'P2', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'T1', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b5', type: 'execute', component: 'callstack', output: 'T2', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'h6', num: 6,
      title: 'Stacked Awaits',
      description: 'Two async functions interleaving',
      hint: 'Each await is a microtask checkpoint — functions interleave at await points.',
      code: [
        { text: 'async function a(){ console.log("a1"); await null; console.log("a2"); }', type: 'promise', color: '#c084fc' },
        { text: 'async function b(){ console.log("b1"); await null; console.log("b2"); }', type: 'promise', color: '#c084fc' },
        { text: 'a(); b(); console.log("sync");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"a1"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"b1"', type: 'sync', target: 'callstack' },
        { id: 'b3', label: '"sync"', type: 'sync', target: 'callstack' },
        { id: 'b4', label: '"a2"', type: 'promise', target: 'microtask' },
        { id: 'b5', label: '"b2"', type: 'promise', target: 'microtask' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4', 'b5'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'a1', animationPath: ['callstack'] },
        { ballId: 'b4', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'b1', animationPath: ['callstack'] },
        { ballId: 'b5', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'sync', animationPath: ['callstack'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'a2', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b5', type: 'execute', component: 'callstack', output: 'b2', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h7', num: 7,
      title: 'Promise.all',
      description: 'Promise.all resolves when all settle — when does .then fire?',
      hint: 'Promise.all itself returns a promise — its .then is a microtask.',
      code: [
        { text: 'console.log("before");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.all([Promise.resolve("x"), Promise.resolve("y")])', type: 'promise', color: '#c084fc' },
        { text: '  .then(([a,b]) => console.log(a, b));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("after");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"before"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"x y"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"after"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'before', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'after', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'x y', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h8', num: 8,
      title: 'The Tricky Order',
      description: 'Six lines — predict all six outputs in order',
      hint: 'Walk through carefully: each setTimeout callback is its own macrotask turn.',
      code: [
        { text: 'console.log("1");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => console.log("2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => { console.log("3"); setTimeout(() => console.log("5"), 0); });', type: 'promise', color: '#c084fc' },
        { text: 'setTimeout(() => console.log("4"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'console.log("6");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"1"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"2"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"3"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"4"', type: 'timeout', target: 'macrotask' },
        { id: 'b5', label: '"5"', type: 'timeout', target: 'macrotask' },
        { id: 'b6', label: '"6"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4', 'b5', 'b6'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: '1', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b6', type: 'execute', component: 'callstack', output: '6', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: '3', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b5', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: '2', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: '4', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b5', type: 'execute', component: 'callstack', output: '5', animationPath: ['macrotask', 'callstack'] },
      ],
    },
    {
      id: 'h9', num: 9,
      title: 'Rejection Handler',
      description: '.catch() is also a microtask',
      hint: '.catch(fn) is syntactic sugar for .then(undefined, fn) — same microtask rules!',
      code: [
        { text: 'console.log("start");', type: 'sync', color: '#4ade80' },
        { text: 'Promise.reject("err").catch(e => console.log("caught:", e));', type: 'promise', color: '#c084fc' },
        { text: 'console.log("end");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"caught"', type: 'promise', target: 'microtask' },
        { id: 'b3', label: '"end"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'end', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'caught: err', animationPath: ['microtask', 'callstack'] },
      ],
    },
    {
      id: 'h10', num: 10,
      title: 'The Final Boss',
      description: 'The ultimate async JavaScript challenge',
      hint: 'Map it out step by step. Microtasks generated inside macrotasks run before the NEXT macrotask.',
      code: [
        { text: 'console.log("start");', type: 'sync', color: '#4ade80' },
        { text: 'setTimeout(() => { console.log("T1"); Promise.resolve().then(() => console.log("P3")); }, 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'Promise.resolve().then(() => console.log("P1")).then(() => console.log("P2"));', type: 'promise', color: '#c084fc' },
        { text: 'setTimeout(() => console.log("T2"), 0);', type: 'timeout', color: '#60a5fa' },
        { text: 'console.log("end");', type: 'sync', color: '#4ade80' },
      ],
      balls: [
        { id: 'b1', label: '"start"', type: 'sync', target: 'callstack' },
        { id: 'b2', label: '"T1"', type: 'timeout', target: 'macrotask' },
        { id: 'b3', label: '"P1"', type: 'promise', target: 'microtask' },
        { id: 'b4', label: '"P2"', type: 'promise', target: 'microtask' },
        { id: 'b5', label: '"T2"', type: 'timeout', target: 'macrotask' },
        { id: 'b6', label: '"P3"', type: 'promise', target: 'microtask' },
        { id: 'b7', label: '"end"', type: 'sync', target: 'callstack' },
      ],
      placementOrder: ['b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7'],
      flow: [
        { ballId: 'b1', type: 'execute', component: 'callstack', output: 'start', animationPath: ['callstack'] },
        { ballId: 'b2', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b3', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b5', type: 'schedule', component: 'macrotask', output: null, animationPath: ['callstack', 'webapi', 'macrotask'] },
        { ballId: 'b7', type: 'execute', component: 'callstack', output: 'end', animationPath: ['callstack'] },
        { ballId: 'b3', type: 'execute', component: 'callstack', output: 'P1', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b4', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b4', type: 'execute', component: 'callstack', output: 'P2', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b2', type: 'execute', component: 'callstack', output: 'T1', animationPath: ['macrotask', 'callstack'] },
        { ballId: 'b6', type: 'schedule', component: 'microtask', output: null, animationPath: ['callstack', 'microtask'] },
        { ballId: 'b6', type: 'execute', component: 'callstack', output: 'P3', animationPath: ['microtask', 'callstack'] },
        { ballId: 'b5', type: 'execute', component: 'callstack', output: 'T2', animationPath: ['macrotask', 'callstack'] },
      ],
    },
  ],
};
